# Generated by Django 5.0.4 on 2024-06-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_image'),
        ('post', '0007_remove_post_post_image_post_post_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category_id',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_images',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_images', to='misc.image'),
        ),
    ]
